name: safety_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.2
  http: ^1.2.2
  
  #pentru harta OpenStreetMap
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  #pentru locatie GPS
  geolocator: ^12.0.0

  #pentru a detecta daca am internet sau nu
  connectivity_plus: ^6.0.0

  #pentru deschis aplicația de SMS cu text precompletat
  url_launcher: ^6.3.0

  # servicii de background (Android foreground service)
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.2.2

  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.1

  #pentru modelul audio de AI
  flutter_audio_capture: ^1.1.11

  tflite_flutter: ^0.12.1

  wakelock_plus: ^1.1.0

  #pentru shake function
  shake: ^3.0.0
  vibration: ^3.1.4
  
  # pentru black box recorder
  camera: ^0.11.0
  path_provider: ^2.1.5
  just_audio: ^0.9.36
  sensors_plus: ^6.0.0

  share_plus: ^7.2.0
  image_picker: ^1.0.0

  audioplayers: ^6.1.0
  audio_session: ^0.1.21
  record: ^6.2.0

  dart_openai: ^6.1.1
  speech_to_text: ^7.0.0
  
  quick_actions: ^1.0.7

  # pentru accesul la contactele din telefon
  flutter_contacts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/1.tflite
    - assets/models/yamnet_class_map.csv
    - assets/sounds/
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_logo.png" 
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  background_image: assets/launch_image.png
  android_12:
    image: assets/launch_image.png
    color: "#FFFFFF"
  fullscreen: true
  android_gravity: center
  ios: true
  web: false 